export const hunt_ficlets = [
    
`It's hard, crawling around the vents. It’s hard, and nobody understands.

You hear a lot of things in the vents. It’s why you carry around your tapes: to keep it all in, and close, and safe. Very safe. Safe with you.

Around here, it’s different, though. These rooms. So many things want to see you. That wanderer. Those lidless eyes. Even those roamers from the West.

The voice in your best friend’s head says it doesn’t exist. You keep it all recorded, though. A mirror stolen on one, a pot roast gone the next. The paint drying room. Rooms moving, changing. 

One says they’d crawl onto your vents, and pretend to be a wild animal.

Saying is not the same as doing, though. 

You welcome them to try.`,

`
01 - NO THREAT

SUBJECT - FLOWER

CAUSE OF DEATH - UNKNOWN (MOUTH DOOR?)

BODY PREVIOUSLY MAULED BY UNKNOWN ENTITY

FLOWER CONSUMED BODY SHORTLY

NO TRACES OF BODY

CONCLUSION - 

HARMLESS. AVOID.


SUBJECT - FRIEND-CLONE

CAUSE OF DEATH - FELL OFF INFINITE STAIRS

‘BRAIN’ INTACT

NO BLOOD (INTENTIONAL?)

METAL BODY

CONCLUSION -

DEFINITELY A ROBOT. NOT A THREAT.

ASK FRIEND IF KILL.

02 - KEEP WATCH

SUBJECT - LURE

CAUSE OF DEATH - ELECTRIC DISCHARGE (CAN’T DO IT AGAIN)

BODY DISPERSED UPON CONTACT

NO TRACES LEFT

CONCLUSION - 

MAYBE DANGEROUS. AVOID.


SUBJECT- NEMESIS 

CAUSE OF DEATH - HAD IT COMING

ARMOR PART OF BODY

ORGANS AVERAGE IF SOMEWHAT LARGE

OVERABUNDANCE OF BLOOD (STORED IN THE ARMOR?)

EYEBALL ARMORS BIOLOGICAL, CAPABLE OF MOVING 30 MINUTES AFTER DEATH 

CONCLUSION -

ANNOYING. GOOD BLOOD. NICE EYEBALLS. AVOID OTHERWISE.

03 - INCREASED WATCH

SUBJECT - STALKER

CAUSE OF DEATH - MIXUP

REVERTS TO ORIGINAL SHAPE AFTER DEATH

PALE, LEATHERY SKIN (BAD FOR CANVAS)

WHITE EYEBALLS, NO IRIS (??)

ORGANS UNKNOWN (TWO HEARTS?)

UPDATE: ORGAN PLACEMENT CHANGES EVERY TIME

CONCLUSION - 

DANGEROUS? DANGEROUS. DISPOSE OF BODY. AVOID. AVOID. 


04 - ABSOLUTELY NOT

SUBJECT - HORROR

CAUSE OF DEATH - REMOTE EXPLOSIVE

WILDLY DIFFERING ORGAN PLACEMENTS

ORGANS MAY HAVE TEETH

EYEBALLS MAY HAVE TEETH

TEETH MAY BE VENOMOUS

MAY NOT EVEN BE DEAD

CONCLUSION -

ENGAGE ONLY IF PREPARED. AVOID. AVOID. AVOID.

SUBJECT- IT IS NOT WHAT IT SEEMS

CAUSE OF DEATH - HE IS NOT DEAD

HE HAS DIED AND HE IS NOT DEAD

HIS BODY STILL SHAMBLES

HIS EYES STILL SHAMBLE

HE IS STILL HERE

CONCLUSION- 

AVOID AVOID AVOID AVOID AVOID


SUBJECT- SLIME

CAUSE OF DEATH - EXPOSURE TO FIRE

BODY COMBUSTED VIOLENTLY UPON EXPOSURE

CONCLUSION-

WE HAVE AN EXPLOSION ROOM NOW

SUBJECT - SELF

CAUSE OF DEATH- HIM

ORGANS NONEXISTING

IT BLEEDS INK

THERE IS A FACE BUT I CANNOT SEE IT

WHERE AM I

IT’S COLD IT’S COLD IT’S COLD IT’S COLD IT’S COLD

CONCLUSION-





TBD - 

GREEN-THING

HAT-WEB

OTHERS?
`


];